### ISSUE TITLE
Add time-traveling debugger

### ISSUE THREAD

**Issue by forki** [fable-compiler/fable-elmish#18] opened 2016-11-18 12:25 UTC
http://elm-lang.org/blog/the-perfect-bug-report

I think I want to give it a shot.

/cc @et1975 @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment] 2016-11-18 12:34
I think @mastoj is already working on something similar for fable-arch.

**Comment by forki** [comment] 2016-11-18 12:38
Cool maybe should join forces. @mastoj Where can I find the current state of the art?

**Comment by mastoj** [comment] 2016-11-18 13:35
Check the plugin sample of fable-arch.

**Comment by forki** [comment] 2016-11-18 13:36
do you hava a link?

**Comment by mastoj** [comment] 2016-11-18 13:38
http://fable.io/fable-arch/samples/plugin/index.html

**Comment by et1975** [comment] 2016-11-18 14:01
I was thinking to check [Redux tools/debugger](https://github.com/gaearon/redux-devtools) needs and see if there could be a layer implemented in `elmish` to make it compatible with that.
If not, see about porting Elm implementation, if it's in Elm (not JS) it is very straight forward. Not sure Elm 0.17 has got the debugger going though.

**Comment by forki** [comment] 2016-11-18 14:01
cool. so where can I read about this thingy? I don't really understand how to use it. Also are you planning to do export/import?

**Comment by forki** [comment] 2016-11-18 14:02
@et AFAIK debugger is in 0.18

**Comment by mastoj** [comment] 2016-11-18 15:26
@sforkmann, I've been thinking about export import, but haven't got the time to do it. Also, I haven't done much with documentation. Basically it's just another app that is running side by side with the applications that listens for all events. I've opened up my abstractions to replay events so the devtools can feed events back to the applications that is being monitored.

**Comment by et1975** [comment] 2016-11-18 15:55
Found the Elm debugger here: https://github.com/elm-lang/virtual-dom/blob/master/src/VirtualDom/Debug.elm

Conceptually, the Elm debugger is a `program` that wraps your `program`, just like my [navigation port does](https://github.com/fable-compiler/fable-elmish/blob/master/src/elmish/elmish-browser-nav.fs). 

It's not much use for elmish as it is however: Since it has visual elements, it has to be split into `core`, `react` (and/or chrome debugger extensions) and `native` parts, to accommodate both browser- and RN- targeting apps. Following on that thought, native already has a way to ship logs and the exported history would be a good fit that.

**Comment by zalmoxisus** [comment] 2016-11-22 12:35
@et1975,
>  I was thinking to check Redux tools/debugger needs and see if there could be a layer implemented in elmish to make it compatible with that.

There's an integration with Redux DevTools Extension: https://twitter.com/FableCompiler/status/772745186287947776

[Redux DevTools Extension can be integrated easily with any architecture](https://medium.com/@zalmoxis/redux-devtools-without-redux-or-how-to-have-a-predictable-state-with-any-architecture-61c5f5a7716f), if you need more details on this, let me know.

**Comment by alfonsogarciacaro** [comment] 2016-11-22 12:55
Fantastic! I love Redux DevTools Extension and actually [it's already possible to use it with Fable](http://fable.io/samples/redux-todomvc/index.html) but being able to use it natively with fable-elmish and fable-arch would be just so awesome. Thanks a lot for your help, @zalmoxisus!

**Comment by zalmoxisus** [comment] 2016-11-22 13:10
@alfonsogarciacaro, you can send messages to it from anywhere via sockets, like [`remote-redux-devtools`](https://github.com/zalmoxisus/remote-redux-devtools) does. [Here](https://github.com/zalmoxisus/remotedev/blob/master/src/devTools.js)'s a simpler js lib you can adopt.

**Comment by et1975** [comment] 2016-11-22 13:34
Looks promising, thanks Mihail!

**Comment by et1975** [comment] 2016-11-22 14:50
@forki Seems the sockets client would be the way to go for hooking up Native debugging. It could go into `elmish` since it doesn't have any React dependencies. If you want to take on this, here's how I see it: a debugger `Program` module that hooks up both `subscribe` (for the debugger events), and `update` to forward updates to the extension. 
The browser nav impl has to be changed as well, since it won't be a root any longer and the final `run` needs to be outside... I can take on that.

**Comment by forki** [comment] 2016-11-22 14:56
Yeah currently I took up another challenge. So I guess this is out of scope
for me right now.

Am 22.11.2016 15:50 schrieb "Eugene Tolmachev" <notifications@github.com>:

@forki <https://github.com/forki> Seems the sockets client would be the way
to go for hooking up Native debugging. It could go into elmish since it
doesn't have any React dependencies. If you want to take on this, here's
how I see it: a debugger Program module that hooks up both subscribe (for
the debugger events), and update to forward updates to the extension.
The browser nav impl has to be changed as well, since it won't be a root
any longer and the final run needs to be outside... I can take on that.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/fable-compiler/fable-elmish/issues/18#issuecomment-262260355>,
or mute the thread

**Comment by et1975** [comment] 2017-01-09 13:58
@zalmoxisus I wonder if I could ask your help investigating the weird behavior I'm seeing.
The [counter sample](https://github.com/et1975/fable-elmish/tree/master/samples/react/counter) in my fork has been updated to use the remotedevtools lib and it used  to work flawlessly, but since upgrading the transpiler and the dependencies and doing a clean build it's completely borked. 

I'm suspecting that either my code or fable is doing something wrong, but I can't tell what.

Symptoms, using the Chrome extension:
- sometimes on init I get `DISPATCH` with no state sent to me
- the actions don't appear in history, although they make it to the extension, as evidenced by the ability to time-travel back. 
- for every one action sent, there appear to be multiple entries recorded (observing the time-travel again)
- fiddling with the the extension, reloading the app, etc sometimes breaks extension - history section is not shown at all and there appears to be no way to bring it back, short of reopening the window.

using the local server and a stand-alone monitor:
- for every one action sent, there appear to be multiple `update` entries recorded.
- all the duplicates added appear to share the same state.

The counter sample has the transpiled F# checked in (in `out` subfolder), so maybe you could tell just by looking. If you decide to give it a spin, you should be able to run with just `yarn install` in the `samples/react` and `yarn start` in the `samples/react/counter` (it will start a local webpack dev server).

Thanks in advance!

**Comment by zalmoxisus** [comment] 2017-01-09 16:59
Hey @et1975,

At first, when trying to open the example, for some reason, I get `null` passed to `window.__REDUX_DEVTOOLS_EXTENSION__.connect`, so it just throws. We're setting `{}` as the default value of the config [here](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/api/index.js#L115), but it works only when nothing is passed as teh argument (or the argument is `undefined`). We could handle `null` as well if it is necessary

> sometimes on init I get DISPATCH with no state sent to me

I guess you're getting `START` not `DISPATCH`, unless you clicked to persist the state. That's my fault. I don't remember why I removed checking for `DISPATCH` [here](https://github.com/zalmoxisus/remotedev/commit/a96ef304db846f61fb98580b87fc5448bb1ea42b#diff-dc93b70e22510613eb83f8bb5ef4aab2L9). Anyway `DISPATCH` not always contains the state, for example when canceling actions, the state should be computed on the client side.

I fixed it in https://github.com/zalmoxisus/remotedev/commit/7650a402f4bb100d03b20459e6e326f42131e70c. Updating to `remotedev@0.2.4` should help. But you should call `extractState(msg)`, instead of `extractState()(msg)` like now in
```js
            var sub = function sub(dispatch) {
                connection.subscribe(function (msg) {
                    var state = __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_5_remotedev__["extractState"])()(msg);
                    program.setState(state)(dispatch);
                });
            };
```

BTW, few days ago, I wrote a [draft of the API](https://github.com/zalmoxisus/remotedev-server/blob/v0.3/docs/API/Realtime.md#5-listening-for-monitor-events), where you can find more details of the types beside `DISPATCH`.

> the actions don't appear in history, although they make it to the extension, as evidenced by the ability to time-travel back.

You're sending `{"Case":"Increment","Fields":[]}` as the action. So, because there's no `type` key, nothing is shown. It should be either a string (which will be interpreted as action type) or an action object which should contain `type` as the key.

> for every one action sent, there appear to be multiple entries recorded (observing the time-travel again)

I don't seem to reproduce that. Just added the `type` key to that object and am getting actions one by one. There's another problem - the state I get for the actions is not actual, but the state before the dispatching occurs.

> fiddling with the the extension, reloading the app, etc sometimes breaks extension - history section is not shown at all and there appears to be no way to bring it back, short of reopening the window.

Could you please check if in this case the extension's script was loaded after you try to call it (check if `window.__REDUX_DEVTOOLS_EXTENSION__` is available from within the code).

> using the local server and a stand-alone monitor: for every one action sent, there appear to be multiple update entries recorded, all the duplicates added appear to share the same state.

That's a sign that you're subscribing to the channel twice. Maybe that [API draft](https://github.com/zalmoxisus/remotedev-server/blob/v0.3/docs/API/Realtime.md#5-listening-for-monitor-events) could help.

**Comment by et1975** [comment] 2017-01-09 18:06
Thank you so much for looking into this!

> I get null passed to window.__REDUX_DEVTOOLS_EXTENSION__.connect, so it just throws.

I went back to the clean repo after submitting the comment to make sure you are able to reproduce and sure enough I hadn't published the version I was discussing. I guess you pulled the repo before I was able to push the update, sorry about that!

>because there's no type key, nothing is shown.

This part confuses me. When everything worked, I had exactly the same action obj sent. It didn't show up as an `update`, but it did show up as a row with the timestamp. Not anymore. I saw your lib augmenting the action with the type, but I guess that happens only for a "remote" case, not "viaExtension"?

> I don't seem to reproduce that. 

That's my bad, I mentioned only the counter example but that's something I observed in `react/todomvc` and `react-native/counter`. I thought it might give some insight into "nothing is shown" problem, but your other comment about subscribing to channel twice makes it unlikely.

> That's a sign that you're subscribing to the channel twice.

I might have a problem somewhere in the initialization, but wouldn't it playback multiple times as opposed to show multiple history entries?

Here's what the extension looks like, once I reload it:
![screen shot 2017-01-09 at 1 00 13 pm](https://cloud.githubusercontent.com/assets/623703/21777217/ee0c036e-d66b-11e6-8469-6cbee86641b1.png)

As you can see in the console output at the bottom, the `window.__REDUX_DEVTOOLS_EXTENSION__` is there, but history and timetravel controls have disappeared.

**Comment by zalmoxisus** [comment] 2017-01-09 19:02
> This part confuses me. When everything worked, I had exactly the same action obj sent. It didn't show up as an `update`, but it did show up as a row with the timestamp.

Yes, it's only [in remotedev](https://github.com/zalmoxisus/remotedev/blob/master/src/devTools.js#L64), not [in the extension](https://github.com/zalmoxisus/redux-devtools-extension/blob/master/src/app/api/index.js#L72). Probably it's worth having a default `type` like this, though we could do even better and add the ability to specify the `type` key in the config like `window.__REDUX_DEVTOOLS_EXTENSION__.connect({ actionTypeKey: 'Case' }`, so for `{"Case":"Increment","Fields":[]}` it would show `Increment`.

> I might have a problem somewhere in the initialization, but wouldn't it playback multiple times as opposed to show multiple history entries?

I was wrong here, it's about emitting not subscribing. Hard to say what could be the reason without a repro.

> Here's what the extension looks like, once I reload it...

Could you please provide some steps to reproduce? I tried to reload several time the app window and the extension window and still not getting that issue. You can press `Cmd+Alt+I` on the extension's window, to see the exception, but it will not help much as the problem should be in the background script.

**Comment by et1975** [comment] 2017-01-09 22:08
> we could do even better and add the ability to specify the type key in the config

that would be pretty sweet, although if I may offer a "functional" twist, define it something like:
`.connect({getType: (a) => a.Case})`

> Could you please provide some steps to reproduce? 

Something like:
- start the SPA
- open dev console
- open the extension
- increment/decrement, try to step back
- close the extension
- open the extension

At this point it's messed up and won't work until I reopen the SPA tab.

**Comment by zalmoxisus** [comment] 2017-01-10 15:45
Could you please try to update the extension? I just published `2.12.1` to Chrome Store, which also includes `getActionType` parameter.

Also I had to change in `fable-elmish-debugger/debugger.js`:

```diff
        var subscribe = function subscribe(model) {
            var sub = function sub(dispatch) {
                connection.subscribe(function (msg) {
-                    var state = extractState()(msg);
+                    var state = extractState(msg);
-                    program.setState(state)(dispatch);
+                    if (typeof state !== 'undefined') program.setState(state)(dispatch);
                });
            };

            return CmdModule.batch(ofArray([ofArray([sub]), program.subscribe(model)]));
        };
```

**Comment by et1975** [comment] 2017-01-10 21:47
@zalmoxisus Thank you, it works!

**Comment by zalmoxisus** [comment] 2017-01-11 10:30
@et1975, glad to know. I've just added that function also in `remotedev@0.2.5`. Will try to unify them after `3.0` release of the extension.

**Comment by et1975** [comment] 2017-01-11 16:29
@zalmoxisus works with Native and local server too! Thanks, Misha!

**Comment by et1975** [comment] 2017-01-11 17:04
And... it is out!

fable-elmish@0.8.0
fable-elmish-react@0.8.0
fable-elmish-debugger@0.1.0

![screen shot 2017-01-11 at 11 33 13 am](https://cloud.githubusercontent.com/assets/623703/21858130/f5fc65ce-d7f5-11e6-8ae0-eb564502f01c.png)

samples/react/counter and samples/react-native/counter have been updated to use the debugger.

**Comment by et1975** [comment] 2017-01-11 17:08
There's a known issue, specifically about the counter samples - it uses a simple `int` for the model, and it doesn't roundtrip properly when the value is `0`. I don't expect anyone to use such a model in real life, so I'm not going to bother fixing it. Closing!

**Closed by et1975** 2017-01-11 17:08 UTC
