### ISSUE TITLE
3.1 breaks Elmish.Bridge

### ISSUE THREAD

**Issue by OnurGumus** [fable-compiler/fable-elmish#206] opened 2020-07-13 11:58 UTC
### Description

When I try to use elmish.bridge with 3.1, it fails with "initialization error", all packages are at latest stable version. Using WSL on Win 10 x64

**Comment by et1975** [comment] 2020-07-13 12:37
Unless someone using Elmish.Bridge is willing to investigate this is not going to get resolved due to the lack of details.

**Comment by OnurGumus** [comment] 2020-07-13 12:56
@et1975 yeah let's keep it as a placeholder till then.

**Comment by MangelMaxime** [comment] 2020-07-15 07:33
@OnurGumus I think you should also open an issue on Elmish.Bridge repository so the maintainers could know/take look at the issue.

**Comment by OnurGumus** [comment] 2020-07-15 08:33
Related issue:
Nhowka/Elmish.Bridge#27

**Comment by et1975** [comment] 2020-07-15 16:32
3.1 adds an error handler around execution of initialization commands and what it means is that you have an unhandled exception in your initialization commands. This is by design and you need to check your initialization logic. Closing.

**Closed as completed by et1975** 2020-07-15 16:32 UTC
